/*Write a program that takes a two digit positive integer and allows the user to perform the following
operations (all these should be in the form of functions):
1. Double the number.
2. Reverse the digits of the number.
3. Raise the number to the power of 2.
4. Sum the digits of the number.
5. If the number is a two-digit number, then raise the first digit to the power of the second digit.

2
Each successive operation should be performed on the number generated by the last operation
(Each function’s output should be the input to the next function). Your program should not contain any
global variables and each of these operations must be implemented by a separate function. Also, your
program should be menu driven.
*/
#include<iostream>
#include<cmath>
using namespace std;
int dOublE (int a );
int rEversE (int a );
int pOwerOfTwo(int a);
int sUm (int a);
int secondpowertofirst (int a);

int main()
{char o;
do
{
int a;
int b;
cout<<"ENTER TWO DIGIT NUMBER \n";
cin>>a;
cout<<"Choose from following option\n1. Double the number.\n2. Reverse the digits of the number.\n3. Raise the number to the power of 2.\n4. Sum the digits of the number.\n5. If the number is a two-digit number, then raise the first digit to the power of the second digit\n\n";
cin>>b;
switch(b)
{
case 1 : cout<<dOublE(a)<<endl;break;
case 2 : cout<<rEversE(a)<<endl; break;
case 3 : cout<<pOwerOfTwo(a)<<endl; break;
case 4 : cout<<sUm(a)<<endl; break;
case 5 : cout<<secondpowertofirst(a)<<endl; break;
default :
    cout<<"Invalid Input \n\n";
}
cout<<"DO YOU WANT TO TRY AGAIN ?\nY for yes and N for no \n";
cin>>o;
}while(o == 'y'||o =='Y');
cout<<"\n\nThank you for Trying. Goodbye!"<<endl;
system("pause >0");
return 0;
}
int dOublE (int a )
{
    return a * 2;
}
int rEversE (int a )
{
    return 10 * (a % 10 ) + a / 10;
}
int pOwerOfTwo (int a)
{
    return pow(a,2);
}
int sUm (int a)
{
    return a/10 + a%10;
}
int secondpowertofirst (int a)
{
    return pow(a%10,a/10);
}
